/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/ErrorMessage/403.vue')['default']
    404: typeof import('./src/components/ErrorMessage/404.vue')['default']
    500: typeof import('./src/components/ErrorMessage/500.vue')['default']
    CheckCard: typeof import('./src/components/CheckCard/index.vue')['default']
    ChooseModule: typeof import('./src/components/ChooseModule/index.vue')['default']
    CodeHighLight: typeof import('./src/components/CodeHighLight/index.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/index.vue')['default']
    ColSetting: typeof import('./src/components/ProTable/components/ColSetting.vue')['default']
    CropUpload: typeof import('./src/components/CropUpload/index.vue')['default']
    DatePicker: typeof import('./src/components/Form/DatePicker/index.vue')['default']
    ECharts: typeof import('./src/components/ECharts/index.vue')['default']
    ESign: typeof import('./src/components/ESign/index.vue')['default']
    FormContainer: typeof import('./src/components/Form/FormContainer/index.vue')['default']
    Grid: typeof import('./src/components/Grid/index.vue')['default']
    GridItem: typeof import('./src/components/Grid/components/GridItem.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MenuSelector: typeof import('./src/components/Selectors/MenuSelector/index.vue')['default']
    OrgSelector: typeof import('./src/components/Selectors/OrgSelector/index.vue')['default']
    Pagination: typeof import('./src/components/ProTable/components/Pagination.vue')['default']
    PositionSelector: typeof import('./src/components/Selectors/PositionSelector/index.vue')['default']
    ProTable: typeof import('./src/components/ProTable/index.vue')['default']
    RoleSelector: typeof import('./src/components/Selectors/RoleSelector/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SButton: typeof import('./src/components/Form/SButton/index.vue')['default']
    SCheckboxGroup: typeof import('./src/components/Form/SCheckboxGroup/index.vue')['default']
    SearchForm: typeof import('./src/components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./src/components/SearchForm/components/SearchFormItem.vue')['default']
    SelectFilter: typeof import('./src/components/SelectFilter/index.vue')['default']
    SelectIcon: typeof import('./src/components/SelectIcon/index.vue')['default']
    SelectIconPlus: typeof import('./src/components/SelectIconPlus/index.vue')['default']
    SFormItem: typeof import('./src/components/Form/SFormItem/index.vue')['default']
    SInput: typeof import('./src/components/Form/SInput/index.vue')['default']
    SRadioGroup: typeof import('./src/components/Form/SRadioGroup/index.vue')['default']
    SSelect: typeof import('./src/components/Form/SSelect/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    SwitchDark: typeof import('./src/components/SwitchDark/index.vue')['default']
    TableColumn: typeof import('./src/components/ProTable/components/TableColumn.vue')['default']
    TreeFilter: typeof import('./src/components/TreeFilter/index.vue')['default']
    UploadFile: typeof import('./src/components/Upload/UploadFile.vue')['default']
    UploadImg: typeof import('./src/components/Upload/UploadImg.vue')['default']
    UploadImgs: typeof import('./src/components/Upload/UploadImgs.vue')['default']
    UserSelector: typeof import('./src/components/Selectors/UserSelector/index.vue')['default']
  }
}
